### ISSUE TITLE
你好，请问这个登录可以跨域吗？ 登录成功是会自动在浏览器设置cookie吗

### ISSUE THREAD

**Issue by ZhangEryi** [cheneyweb/xserver#1]
如题，我基本按照您的代码，然后可以登录成功，不过没有设置cookie  也没有登录状态 不知道为什么

**Comment by ZhangEryi** [comment]
哦 知道了 这个session 只会设置cookie  跨域就搞不定了设置不上

**Comment by cheneyweb** [comment]
登录认证目前采用了三种方案：
1、本地session，这种方案依赖于cookie和本地主机内存，实现最简单，但是无法解决跨域
2、redis服务，这种方案使用redis维护用户登录信息，全系统通用，可以解决跨域问题
3、json web token，这种方案基于TOKEN口令令牌，无须维护session与token，无须维护与用户连接，只需要关心token过期时间，该方案安全高效稳定，比较适合微服务或Serverless架构，个人推荐
以上三种方案在x-koa项目工程内均有基础实现，可自由选择
